pipeline:


  pypi_publish:
    secrets:
      - username
      - password
    image: gjtempleton/drone-pypi
    repository: http://pypi.intelligems.eu/
    distributions:
      - sdist
    setupfile: setup.py
    when:
      branch: master
      event: push


  slack:
    image: plugins/slack
    secrets:
      - slack_webhook
    webhook: ${SLACK_WEBHOOK}
    channel: ci-messages
    username: drone
    template: >
      {{#success build.status}}
        *{{build.status}}* {{repo.name}} <{{build.link}}|{{build.number}}>. Profit?
        Author: {{build.author}}
        Commit: <${DRONE_COMMIT_LINK}|{{repo.owner}}/{{repo.name}}#${DRONE_COMMIT:0:8}> `${DRONE_COMMIT_MESSAGE}`
        Trigger event: {{build.event}} ({{build.branch}})
      {{else}}
        *{{build.status}}* {{repo.name}} <{{build.link}}|{{build.number}}>. Go home fork, you're drunk.
        Author: {{build.author}}
        Commit: <${DRONE_COMMIT_LINK}|{{repo.owner}}/{{repo.name}}#${DRONE_COMMIT:0:8}> `${DRONE_COMMIT_MESSAGE}`
        Trigger event: {{build.event}} ({{build.branch}})
      {{/success}}
    when:
      status: [ success, failure ]
